[package]
name = "snesimage"
version = "0.1.0"
authors = ["Jason Lynch <jason@aexoden.com>"]
description = "Tool to optimize images for use on the SNES"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.46.0"
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
clap = { version = "4.2.1", features = ["derive"] }
cogset = "0.2"
fern = { version = "0.6", features = ["colored"] }
image = "0.24.6"
log = "0.4"
palette = "0.7.6"
rand = "0.8.5"
rgb = "0.8"
sdl2 = "0.36.0"
serde_json = "1.0.109"
ssimulacra2 = "0.5.0"
