[package]
name = "snesimage"
version = "0.1.0"
authors = ["Jason Lynch <jason@aexoden.com>"]
description = "Tool to optimize images for use on the SNES"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.42"
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
clap = { version = "4.2.1", features = ["derive"] }
cogset = "0.2"
dssim-core = "3.1"
fern = { version = "0.6", features = ["colored"] }
image = "0.24"
log = "0.4"
palette = "0.6.1"
rand = "0.8.5"
rgb = "0.8"
sdl2 = "0.35.2"
serde_json = "1.0.95"
